### ISSUE TITLE
centos 7 no libsctp.so

### ISSUE THREAD

**Issue by Jovons** [Orange-OpenSource/diafuzzer#6]
for those who have problems with sctp multihoming:
 **./fuzz.py -h
Traceback (most recent call last):
  File "./fuzz.py", line 25, in <module>
    import sctp
  File "/home/jovons/diafuzzer/sctp.py", line 26, in <module>
    libsctp = ctypes.CDLL('libsctp.so')
  File "/usr/lib64/python2.7/ctypes/__init__.py", line 360, in __init__
    self._handle = _dlopen(self._name, mode)**

change `libsctp = ctypes.CDLL('libsctp.so')` to `libsctp = ctypes.CDLL('libsctp.so.1')`

now start sctp multihoming:
./fuzz.py --local-addresses '172.28.15.15','172.28.15.254' --local-port 3868 server scenarios/S6a_CER.scn

and can see:

![image](https://user-images.githubusercontent.com/3646400/47059604-a9785700-d1fc-11e8-8756-2f2cf1192c74.png)

**Comment by gte-itnsec** [comment]
Dear Jovons,

Thank you for highlighting this issue.

While the required shared library is installed by lksctp-tools, the link used by `sctp.py` is only created by lkstp-tools-devel.

The problem can be solved either by:

* installing lksctp-tools-devel, and leave the source code as is
* modifying `sctp.py` the way you did, to load the specific version of libsctp

For sake of simplicity, I will modify `sctp.py` in order to handle both .so and .so.1, while giving preference to the .so variant.
